spring:
  datasource:
    # DB Credentials (DEFAULT VALUES FOR DEVELOPMENT ONLY)
    url: ${DB_URL:jdbc:postgresql://localhost:5433/pointOfSaleDatabase?prepareThreshold=0}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:KxQwerAdFS156}
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      # This secret key is for local testing only, doesn't matter if this gets pushed in the repository
      # Just make sure not to provide this value under any environments in the repository
      secret-key: ${SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
#      secret-key: ${SECRET_KEY}
      expiration: 86400000 # one day
      refresh-token:
        expiration:  604800000 # one week

logging:
  level:
    org.springframework.security: DEBUG
#
#server:
#  port: 8080

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}